version: "3.7"

services:
  sn-pwa:
    container_name: sn-pwa
    ports:
      - 3000:3000
    build: ./
    volumes:
      - /opt/app/node_modules
      - /opt/app/.next
    env_file: ./.env.development
